version: '3.8'
services:
  gym-db:
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_DB: gym
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      timeout: 60s
      retries: 10
  gym-api:
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://gym-db:5432/gym
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "9090:8080"
    depends_on:
      gym-db:
        condition: service_healthy
